[en]
    contentDir = 'content'
    disabled = false
    locale = 'en-US'
    direction = 'ltr'
    label = 'English'
    title = 'Portfolio'
    weight = 0
[it]
    contentDir = 'content'
    disabled = false
    locale = 'it-iT'
    direction = 'ltr'
    label = 'Italian'
    title = 'Portfolio'
    weight = 1

